name: runs scrape.py

on:
  schedule:
    - cron: '30 22 * * *' # 00 17 * * *

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:

      - name: check repository content
        uses: actions/checkout@v3

      - name: install python
        uses: actions/setup-python@v4

      - name: install packages
        run: python -m pip install pip install -r requirements.txt

      - name: setup chromedriver
        uses: nanasess/setup-chromedriver@master
        with:
          chromedriver_version: 'latest'

      - name: execute scraping
        env: 
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python scrape.py