name: runs scrape.py

on:
  schedule:
    - cron: '00 20 * * *' 
  workflow_dispatch:

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install Chrome and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip xvfb libxi6 libgconf-2-4 google-chrome-stable
          python -m pip install webdriver-manager

      - name: Set up ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+')
          CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          wget -N "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip -d /usr/local/bin/
          rm chromedriver_linux64.zip

      - name: Set up Xvfb
        run: |
          Xvfb :99 -ac -screen 0 1280x1024x24 > /dev/null 2>&1 &
          export DISPLAY=:99

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Execute scraping
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          SENDER: ${{ secrets.SENDER }}
          RECIEVER: ${{ secrets.RECIEVER }}
        run: python scrape.py
