name: runs scrape.py

on:
  schedule:
    - cron: '00 20 * * *' 
  workflow_dispatch:

jobs:
  run_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository content
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Install dependencies
        run: python -m pip install -r requirements.txt

      - name: Set up Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          python -m pip install webdriver-manager
          
      - name: Execute scraping
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
          SENDER: ${{ secrets.SENDER }}
          RECIEVER: ${{ secrets.RECIEVER }}
        run: python scrape.py
